CREATE TABLE DISCIPLINAS(
   TIPO_ELETIVA VARCHAR(13) NOT NULL PRIMARY KEY
  ,COD_ELETIVA  VARCHAR(7) NOT NULL
  ,NOME_ELETIVA VARCHAR(95) NOT NULL
  ,DIA_SEMANA   INTEGER  NOT NULL
  ,CH           INTEGER  NOT NULL
);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-001','BIG DATA COM FOCO EM NEGÓCIOS',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-015','BLOCKCHAIN E CRIPTOMOEDAS',6,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-002','CONSTRUÇÃO DE ESCALAS E SEGMENTAÇÃO DE MERCADO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-003','CONSTRUINDO UM FUTURO MELHOR: VIVENCIANDO NEGÓCIOS DE IMPACTO SOCIAL',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-004','DIAGNÓSTICO FINANCEIRO DO NEGÓCIO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-005','DIREÇÃO DE CINEMA: TÉCNICA, CONCEITO E APLICAÇÃO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-006','DIVERSIDADE: O GRANDE DESAFIO CONTEMPORÂNEO DA SOCIEDADE E DAS EMPRESAS',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-007','ECONOMIA CRIATIVA',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-008','EMPREENDENDO COM EMOÇÃO: VIVENCIANDO UMA STARTUP',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-009','EXPRESSÃO E COMUNICAÇÃO : PRÁTICAS DE APRESENTAÇÃO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-003','GEOMARKETING',6,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-010','GESTÃO DA PEQUENA E MÉDIA EMPRESA',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-011','INOVAÇÃO E O COMPORTAMENTO DO CONSUMIDOR: MINIMIZANDO RISCOS DE FRACASSO EM PRODUTOS INOVADORES',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-012','INTERNATIONAL ORGANIZATIONAL BEHAVIOR AND MULTI-CULTURAL BUSINESS ENVIRONMENTS',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-013','LÍDER-COACH: PREPARANDO-SE PARA A LIDERANÇA DO SÉCULO XXI',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-014','MARKETING E A GESTÃO DA EXPERIÊNCIA DO CLIENTE',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-015','MITOS E SÍMBOLOS NA PRODUÇÃO DA CULTURA',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-016','MODA, CONSUMO E COMPORTAMENTO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-017','NEGOCIAÇÃO EXECUTIVA EMPRESARIAL E GESTÃO DE CONFLITOS',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-018','NEUROCIÊNCIA APLICADA AO MERCADO',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_ESPM','ELE-019','VISÕES DO CONTEMPORÂNEO: REFLEXÕES SOBRE A SOCIEDADE, A CULTURA E A POLÍTICA NO SÉCULO XXI',6,36);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-010','ANIMAÇÃO 3D',4,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-002','BUSINESS INTELLIGENCE I',3,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-007','COMPUTAÇÃO COGNITIVA',6,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-005','CRM',4,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-008','GAME ENGINE',3,72);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-018','PROGRAMAÇÃO MOBILE',9,144);
INSERT INTO DISCIPLINAS(TIPO_ELETIVA,COD_ELETIVA,NOME_ELETIVA,DIA_SEMANA,CH) VALUES ('ELETIVAS_TECH','TEL-011','ANÁLISE DE JOGOS',6,72);
